name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push udagram-api-feed
        run: |
          cd udagram-api-feed
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-feed:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-feed:latest

      - name: Build and push udagram-api-user
        run: |
          cd ../udagram-api-user
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-api-user:latest

      - name: Build and push udagram-frontend
        run: |
          cd ../udagram-frontend
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-frontend:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-frontend:latest

      - name: Build and push udagram-reverseproxy
        run: |
          cd ../udagram-reverseproxy
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-reverseproxy:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/udagram-reverseproxy:latest
